apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: findit-ingress
  namespace: findit
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/websocket-services: "findit-backend"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: findit-backend
                port:
                  number: 80
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: findit-backend
                port:
                  number: 80
          - path: /uploads
            pathType: Prefix
            backend:
              service:
                name: findit-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: findit-frontend
                port:
                  number: 80
